#!/bin/bash
hadoop fs -mkdir -p /user/ankita/MR/input
hadoop fs -put twitterData.txt /user/ankita/MR/input
hadoop fs -ls /user/ankita/MR/input
hadoop fs -rm /user/ankita/MR/output/*
hadoop fs -rmdir /user/ankita/MR/output
hadoop jar /usr/lib/hadoop-mapreduce/hadoop-streaming-2.6.0-cdh5.7.0.jar -file /src/cwc_mapper.py -mapper /src/cwc_mapper.py -file /src/cwc_reducer.py -reducer /src/cwc_reducer.py -input /user/ankita/MR/input/* -output /user/ankita/MR/output
hadoop fs -cat /user/ankita/MR/output/part*
hadoop fs -get /user/ankita/MR/output/ /src/
